//example main function that uses the potentiometer control MuxedPot class
//this main function should also include the autogenerated code from STM32CubeIDE
//the generated code was left out for readability

#include "MuxedPots.hpp"
#include "weights.hpp"

int main(){

    // --- Initialize the CS pin ---
    MuxedPots pot(&hspi1, GPIOA, GPIO_PIN_0); //initializes the CS pin

    // --- Demo Use ---
    pot.shutdownAll(); //shutsdown all pots, 0ohms/power-saving mode

    pot.setBit(0,0,127); // sets CS122 to half resistance ~25kOhm
    
    pot.setResistance(1,5,25000); // sets CS142 to half resistance ~25kOhm

    pot.shutdown(2,10); //puts CS221 in shutdown mode

    while(1){
        //main loop
    }


}